add_executable(cgx1_model main.cpp)
add_executable(cgx1_model_tests tests.cpp)
add_executable(cgx1_workgroup_scheduler_tests workgroup_scheduler_tests.cpp)
add_executable(cgx1_cu_dispatch_scheduler_tests cu_dispatch_scheduler_tests.cpp)
add_executable(cgx1_command_queue_runtime_tests command_queue_runtime_tests.cpp)

target_include_directories(cgx1_model PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(cgx1_model_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(cgx1_workgroup_scheduler_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(cgx1_cu_dispatch_scheduler_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(cgx1_command_queue_runtime_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

add_test(NAME cgx1_model_checks COMMAND cgx1_model_tests)
add_test(NAME cgx1_workgroup_scheduler_checks COMMAND cgx1_workgroup_scheduler_tests)
add_test(NAME cgx1_cu_dispatch_scheduler_checks COMMAND cgx1_cu_dispatch_scheduler_tests)
add_test(NAME cgx1_command_queue_runtime_checks COMMAND cgx1_command_queue_runtime_tests)
